name: Deploy to development environment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REACT_APP_OPEN_AI_URL: ${{ secrets.REACT_APP_OPEN_AI_URL_DEV }}

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  deploy-app-to-dev:
    name: Deploy app to Development
    runs-on: ubuntu-latest
    steps:
      - name: Text Analysis App
        uses: graasp/graasp-deploy/.github/actions/deploy-dev-s3-apps@37170fda9ae9f38fafb70441e152274f3cd0d197
        with:
          build-folder: 'build'
          version: 'latest'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.APPS_AWS_REGION }}
          aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME_APPS_DEV }}
          cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_APPS_DEV }}
          app-id: ${{ secrets.APP_ID }}
          graasp-domain: ${{ secrets.REACT_APP_DOMAIN_DEV }}
          sentry-dsn: ${{ secrets.SENTRY_DSN }}
